(() => {
'use strict';
const $=s=>document.querySelector(s), E=window.GameEngine, tiles=window.BOARD;
const colors=['#f6cd58','#abcaff','#f2a6bb','#9dddbe','#c5b5f4','#ffa971','#b6e8ed','#e3ddae'];
const storageKey='original-party-board-v1';
let state=null,undo=null,busy=false,zoom=1,viewed=null,playingEvent=false,extraRoll=false;
function save(){try{localStorage.setItem(storageKey,JSON.stringify({state,undo,extraRoll}))}catch(e){$('#notice').textContent='浏览器未允许保存进度；请保持此页面打开。'}}
function restore(){try{const s=JSON.parse(localStorage.getItem(storageKey));if(s&&s.state?.version===1&&s.state.players.length>=2&&s.state.players.length<=8&&s.state.players.every(p=>typeof p.name==='string'&&Number.isInteger(p.pos)&&p.pos>=0&&p.pos<=49)&&s.state.players[s.state.turn]){state=s.state;undo=s.undo;extraRoll=!!s.extraRoll}}catch(e){}}
function button(text,fn,primary=false){const el=document.createElement('button');el.textContent=text;if(primary)el.className='primary';el.onclick=fn;return el}
function optionSelect(label,options){const l=document.createElement('label');l.textContent=label;const el=document.createElement('select');el.setAttribute('aria-label',label);options.forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;el.append(o)});$('#eventOptions').append(l,el);return el}
function otherPlayers(){return state.players.filter(p=>p.id!==state.turn).map(p=>[p.id,p.name])}
function active(){return state.players[state.turn]}
function note(text){state.notes.unshift(text);state.notes=state.notes.slice(0,12);$('#notice').textContent=text}
function renderBoard(){const spaces=$('#spaces');spaces.replaceChildren();tiles.forEach(t=>{const b=button('',()=>showTile(t.id,false));b.className='space';b.style.left=t.x+'%';b.style.top=t.y+'%';b.setAttribute('aria-label',`${t.id===0?'起点':'第'+t.id+'格'}：${t.title}`);b.dataset.id=t.id;const n=document.createElement('span');n.textContent=t.id===0?'起':t.id===49?'终':t.id;b.append(n);spaces.append(b)});}
function render(){const ps=$('#pieces');ps.replaceChildren();document.querySelectorAll('.space').forEach(b=>b.classList.toggle('selected',!!state&&Number(b.dataset.id)===active().pos));if(!state)return;const occupied={};state.players.forEach(p=>{const t=tiles[p.pos],idx=occupied[p.pos]||0;occupied[p.pos]=idx+1;const dot=document.createElement('div');dot.className='piece'+(p.id===state.turn?' active':'');dot.style.background=colors[p.id];dot.style.left=`calc(${t.x}% + ${(idx%3-1)*13}px)`;dot.style.top=`calc(${t.y}% + ${Math.floor(idx/3)*15}px)`;dot.textContent=p.id+1;dot.title=p.name;dot.dataset.player=p.id;ps.append(dot)});$('#players').replaceChildren();state.players.forEach(p=>{const row=document.createElement('div');row.className='player-row'+(p.id===state.turn?' active':'');const dot=document.createElement('span');dot.className='dot';dot.style.background=colors[p.id];dot.textContent=p.id+1;const name=document.createElement('span');name.className='name';name.textContent=p.name+(p.shield?' · 免酒×'+p.shield:'')+(p.minus?' · 下轮−1':'');const pos=document.createElement('small');pos.textContent=p.pos===0?'起点':p.pos===49?'终点':p.pos+' / 49';row.append(dot,name,pos);$('#players').append(row)});$('#currentName').textContent=active().name;$('#position').textContent=active().pos===0?'START · 准备出发':`第 ${active().pos} 格 · ${tiles[active().pos].title}`;$('#round').textContent=`第 ${state.round} 轮`;$('#dice').textContent=state.dice?['','⚀','⚁','⚂','⚃','⚄','⚅'][state.dice]:'⚄';$('#dice').setAttribute('aria-label',state.dice?`骰子点数 ${state.dice}`:'准备掷骰');$('#roll').textContent=state.ended?'本局结束 · 再来一局':busy?'棋子移动中…':state.pending?'继续处理当前格':extraRoll?'再掷一次骰子':'掷骰子';$('#roll').disabled=busy;$('#undo').hidden=!undo;$('#newGame').textContent='重新开局';if(state.notes.length)$('#notice').textContent=state.notes[0];}
function setup(){if(busy)return;$('#nameInputs').replaceChildren();(state?state.players.map(p=>p.name):['玩家1','玩家2','玩家3','玩家4']).forEach(addName);$('#setupError').textContent='';$('#setup').showModal()}
function addName(name=''){const list=$('#nameInputs'),id=list.children.length+1;if(id>8)return;const row=document.createElement('div');row.className='name-input';const label=document.createElement('label');label.textContent='玩家 '+id;const input=document.createElement('input');input.value=name;input.placeholder='输入名字';input.maxLength=12;input.setAttribute('aria-label','玩家 '+id+' 的名字');const remove=button('×',()=>{if(list.children.length>2)row.remove();$('#addPlayer').disabled=list.children.length>=8});remove.type='button';remove.setAttribute('aria-label','移除此玩家');row.append(label,input,remove);list.append(row);$('#addPlayer').disabled=id>=8}
$('#addPlayer').onclick=()=>addName();$('#newGame').onclick=setup;$('#closeSetup').onclick=()=>$('#setup').close();
$('#setupForm').onsubmit=e=>{e.preventDefault();const names=[...$('#nameInputs').querySelectorAll('input')].map((x,i)=>x.value.trim()||'玩家'+(i+1));if(new Set(names).size!==names.length){$('#setupError').textContent='名字重复了，请换一个名字。';return}if(state&&!state.ended&&!confirm('重新开局会清除当前棋盘进度，确定吗？'))return;state=E.create(names);undo=null;extraRoll=false;note('从 START 出发。掷骰后沿原路线前进。');save();render();$('#setup').close()};
function randomDie(){const a=new Uint32Array(1);let n;do{crypto.getRandomValues(a);n=a[0]}while(n>=4294967292);return n%6+1}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function roll(){if(busy)return;if(!state||state.ended){setup();return}if(state.pending){showTile(state.pending.tile,true);return}busy=true;undo=JSON.parse(JSON.stringify({state,extraRoll}));const value=randomDie();const from=active().pos;const path=E.roll(state,value,extraRoll);extraRoll=false;save();render();$('#dice').classList.add('rolling');for(let i=0;i<7;i++){$('#dice').textContent=['⚀','⚁','⚂','⚃','⚄','⚅'][i%6];await sleep(70)}$('#dice').classList.remove('rolling');active().pos=from;for(const p of path){active().pos=p;render();await sleep(140)}const notes=[];if(state.bomb){if(state.bomb.value===value)notes.push(`${active().name} 摇中数字炸弹 ${value}，喝1杯。`);state.bomb=null}if(state.prediction){const right=(value%2===1?'odd':'even')===state.prediction.value;notes.push(`${state.prediction.name} 的单双预言${right?'猜对了':'猜错了，喝1杯'}。`);state.prediction=null}notes.push(`${active().name} 掷出 ${value} 点，前进 ${state.pending.steps} 步，停在「${tiles[active().pos].title}」。`);note(notes.join('\n'));busy=false;save();render();showTile(active().pos,true)}
$('#roll').onclick=roll;
function finishTurn(){const p=active();if(p.pos===49){state.ended=true;state.pending=null;note(`${p.name} 到达终点。其余玩家一起喝完终点杯，本局结束。`)}else{E.next(state);extraRoll=false}$('#event').close();save();render()}
function resolveMove(pos,message){active().pos=pos;note(message);finishTurn()}
function showTile(id,playing){viewed=id;playingEvent=playing;const t=tiles[id];$('#eventNumber').textContent=id===0?'START':id===49?'FINISH':`第 ${String(id).padStart(2,'0')} 格 / 49`;$('#eventTitle').textContent=t.title;$('#eventText').textContent=t.text;$('#eventSymbol').textContent=({question:'?',chance:'!',safe:'⌂',game:'🎮',duel:'🎮',pour:'▱',reroll:'⚄',backroll:'⚄',finish:'🏁'})[t.type]||'';$('#eventOptions').replaceChildren();$('#eventActions').replaceChildren();const acts=$('#eventActions');const links={question:['真心话 / 大冒险','tod_setup'],chance:['命运摇摇乐','slot_machine'],game:['派对小游戏','mini_games_menu'],duel:['PK 小游戏','mini_games_menu']};if(links[t.type]){const a=document.createElement('a');a.textContent='打开原版'+links[t.type][0];a.href='https://unitp.cc/#'+links[t.type][1];a.target='_blank';a.rel='noopener';acts.append(a)}
 if(!playing){acts.append(button('返回棋盘',()=>$('#event').close(),true));if(!$('#event').open)$('#event').showModal();return}
 const add=(text,fn,primary=false)=>acts.append(button(text,fn,primary));
 switch(t.type){
 case 'partner': {const target=state.players.filter(p=>p.id!==state.turn)[Math.floor(Math.random()*(state.players.length-1))];if(!state.pending.target){state.pending.target=target.id;save()}const p=state.players[state.pending.target];const l=document.createElement('p');l.className='muted';l.textContent='本次随机玩家：'+p.name;$('#eventOptions').append(l);break}
 case 'minus': add('已完成 · 下轮点数−1',()=>{active().minus=1;finishTurn()},true);break;
 case 'lucky': add('后退3格 · 获得免酒权',()=>{active().shield++;resolveMove(Math.max(0,active().pos-3),active().name+' 后退3格，获得一次免酒权。')},true);break;
 case 'reroll': add('再掷一次',()=>{state.pending=null;extraRoll=true;$('#event').close();save();render()},true);add('喝1杯 · 下一位',finishTurn);break;
 case 'backroll': add('掷骰并后退',()=>{const n=randomDie();state.dice=n;resolveMove(Math.max(0,active().pos-n),active().name+' 后退骰子为 '+n+'，后退 '+n+' 格。')},true);break;
 case 'photo': add('合影完成 · 下一位',finishTurn,true);add('被拒 · 后退2格',()=>resolveMove(Math.max(0,active().pos-2),'合影被拒，后退2格。'));break;
 case 'swap': {const sel=optionSelect('选择交换位置的玩家',otherPlayers());add('同意 · 交换棋子',()=>{const target=state.players[Number(sel.value)],p=active();[target.pos,p.pos]=[p.pos,target.pos];note(p.name+' 与 '+target.name+' 交换位置。成功，你罚1杯。');finishTurn()},true);add('被拒 · 对方罚1杯',finishTurn);break}
 case 'pull': {const n=state.players.length,indices=[(state.turn-1+n)%n,(state.turn+1)%n],opts=[...new Set(indices)].map(i=>[i,state.players[i].name]);const sel=optionSelect('选择左边或右边的玩家（按设置顺序）',opts);add('拉到本格 · 对方喝1杯',()=>{state.players[Number(sel.value)].pos=active().pos;finishTurn()},true);break}
 case 'bomb': {const sel=optionSelect('指定骰子数字',[1,2,3,4,5,6].map(n=>[n,String(n)]));add('确定数字 · 下一位',()=>{state.bomb={value:Number(sel.value)};finishTurn()},true);break}
 case 'predict': {const sel=optionSelect('盲猜下一位骰子的单双',[['odd','单数'],['even','双数']]);add('记下预言 · 下一位',()=>{state.prediction={name:active().name,value:sel.value};finishTurn()},true);break}
 case 'twin': {const sel=optionSelect('选择你的搭子',otherPlayers());add('选好搭子 · 下一位',()=>{state.twins.push({a:state.turn,b:Number(sel.value),until:state.round+2});note(active().name+' 与 '+state.players[Number(sel.value)].name+' 接下来两轮一起喝。');finishTurn()},true);break}
 default: break;
 }
 const custom=['minus','lucky','reroll','backroll','photo','swap','pull','bomb','predict','twin'];if(!custom.includes(t.type))add(t.type==='finish'?'确认终点 · 结束本局':t.type==='safe'?'安全通过 · 下一位':'已完成 · 下一位',finishTurn,true);
 if(active().shield>0&&t.type!=='finish'&&t.type!=='safe'){add('使用一次免酒权',()=>{active().shield--;note(active().name+' 使用了一次免酒权；其余任务仍按格子规则执行。');save();render();showTile(id,true)})}
 if(state.twins.length){const reminder=document.createElement('p');reminder.className='fine';reminder.textContent=state.twins.map(t=>`${state.players[t.a].name} + ${state.players[t.b].name}：连体婴，谁输都一起喝`).join('；');$('#eventOptions').append(reminder)}
 if(!$('#event').open)$('#event').showModal();
}
$('#closeEvent').onclick=()=>$('#event').close();
$('#undo').onclick=()=>{if(busy||!undo)return;if(!confirm('撤销上次掷骰及其后续操作？'))return;state=undo.state;extraRoll=undo.extraRoll;undo=null;$('#event').close();save();render()};
function setZoom(value){zoom=Math.max(1,Math.min(3,value));$('#board').style.width=zoom*100+'%';$('#zoomOut').disabled=zoom===1;$('#zoomIn').disabled=zoom===3}
$('#zoomIn').onclick=()=>setZoom(zoom+.5);$('#zoomOut').onclick=()=>setZoom(zoom-.5);$('#fit').onclick=()=>{setZoom(1);$('#viewport').scrollTo(0,0)};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&!busy)save()});
renderBoard();restore();render();setZoom(1);
})();
